import 'package:get/get.dart';
import 'package:untitled/localization/allLanguages.dart';
import 'package:untitled/localization/languages/arabic.dart';
import 'package:untitled/localization/languages/chinese.dart';
import 'package:untitled/localization/languages/danish.dart';
import 'package:untitled/localization/languages/dutch.dart';
import 'package:untitled/localization/languages/english.dart';
import 'package:untitled/localization/languages/french.dart';
import 'package:untitled/localization/languages/german.dart';
import 'package:untitled/localization/languages/greek.dart';
import 'package:untitled/localization/languages/hindi.dart';
import 'package:untitled/localization/languages/indonesian.dart';
import 'package:untitled/localization/languages/italian.dart';
import 'package:untitled/localization/languages/japanese.dart';
import 'package:untitled/localization/languages/korean.dart';
import 'package:untitled/localization/languages/norwegian.dart';
import 'package:untitled/localization/languages/polish.dart';
import 'package:untitled/localization/languages/portuguese.dart';
import 'package:untitled/localization/languages/russian.dart';
import 'package:untitled/localization/languages/spanish.dart';
import 'package:untitled/localization/languages/swedish.dart';
import 'package:untitled/localization/languages/thai.dart';
import 'package:untitled/localization/languages/turkish.dart';
import 'package:untitled/localization/languages/vietnamese.dart';

class LKeys {
  static const textChatDedicated = "textChatDedicated";
  static const socialMedia = "socialMedia";
  static const chatRoom = "chatRoom";
  static const chatRoomDesc = "chatRoomDesc";
  static const randomRoom = "randomRoom";
  static const randomRoomDesc = "randomRoomDesc";
  static const craftYourProfile = "craftYourProfile";
  static const craftYourProfileDesc = "craftYourProfileDesc";
  static const createChatPost = "createChatPost";
  static const createChatPostDesc = "createChatPostDesc";
  static const letsStart = "letsStart";
  static const signInTo = "signInTo";
  static const continue1 = "continue1";
  static const signInDesc = "signInDesc";
  static const signInWithGoogle = "signInWithGoogle";
  static const signInWithEmail = "signInWithEmail";
  static const signInWithApple = "signInWithApple";
  static const bySelectingAgree = "bySelectingAgree";
  static const iAgreeTo = "iAgreeTo";
  static const termsOfUse = "termsOfUse";
  static const and = "and";
  static const privacyPolicy = "privacyPolicy";
  static const selectYour = "selectYour";
  static const interests = "interests";
  static const interestsDesc = "interestsDesc";
  static const setYour = "setYour";
  static const username = "username";
  static const setUsernameDesc = "setUsernameDesc";
  static const thisUsernameIsNotAvailable = "thisUsernameIsNotAvailable";
  static const thisUsernameIsAvailable = "thisUsernameIsAvailable";
  static const profilePicture = "profilePicture";
  static const setProfileDesc = "setProfileDesc";
  static const feed = "feed";
  static const rooms = "rooms";
  static const randoms = "randoms";
  static const chats = "chats";
  static const profile = "profile";
  static const comments = "comments";
  static const writeSomething = "writeSomething";
  static const share = "share";
  static const report = "report";
  static const exploreBy = "exploreBy";
  static const members = "members";
  static const roomsBy = "roomsBy";
  static const requestToJoin = "requestToJoin";
  static const requested = "requested";
  static const requestToJoinThisRoom = "requestToJoinThisRoom";
  static const requestToJoinDesc = "requestToJoinDesc";
  static const joinThisRoom = "joinThisRoom";
  static const searching = "searching";
  static const searchingDesc = "searchingDesc";
  static const found = "found";
  static const next = "next";
  static const viewFullProfile = "viewFullProfile";
  static const followers = "followers";
  static const follow = "follow";
  static const following = "following";
  static const unFollow = "unFollow";
  static const delete = "delete";
  static const profileSetting = "profileSetting";
  static const editProfile = "editProfile";
  static const roomsYouOwn = "roomsYouOwn";
  static const notification = "notification";
  static const profileVerification = "profileVerification";
  static const pushNotification = "pushNotification";
  static const pushNotificationDesc = "pushNotificationDesc";
  static const getInvitedToRooms = "getInvitedToRooms";
  static const getInvitedToRoomsDesc = "getInvitedToRoomsDesc";
  static const helpSupport = "helpSupport";
  static const logOut = "logOut";
  static const deleteMyAcc = "deleteMyAcc";
  static const version = "version";
  static const roomsInvitation = "roomsInvitation";
  static const createNewRoom = "createNewRoom";
  static const selectProfileImage = "selectProfileImage";
  static const selectBackgroundImage = "selectBackgroundImage";
  static const roomName = "roomName";
  static const shortDescription = "shortDescription";
  static const selectTag = "selectTag";
  static const createRoom = "createRoom";
  static const whatIsYourRoomAbout = "whatIsYourRoomAbout";
  static const makeRoomPublic = "makeRoomPublic";
  static const makeRoomPublicDesc = "makeRoomPublicDesc";
  static const joinAfterRequest = "joinAfterRequest";
  static const joinAfterRequestDesc = "joinAfterRequestDesc";
  static const invitedBy = "invitedBy";
  static const addPost = "addPost";
  static const post = "post";
  static const writeHere = "writeHere";
  static const requests = "requests";
  static const block = "block";
  static const reject = "reject";
  static const accept = "accept";
  static const acceptInvitation = "acceptInvitation";
  static const requestDesc = "requestDesc";
  static const roomInfo = "roomInfo";
  static const muteNotification = "muteNotification";
  static const clearChat = "clearChat";
  static const inviteSomeone = "inviteSomeone";
  static const shareThisRoom = "shareThisRoom";
  static const reportRoom = "reportRoom";
  static const leaveThisRoom = "leaveThisRoom";
  static const roomSettings = "roomSettings";
  static const joinRequests = "joinRequests";
  static const roomMembers = "roomMembers";
  static const deleteThisRoom = "deleteThisRoom";
  static const createdOn = "createdOn";
  static const createdBy = "createdBy";
  static const leaveRoomDesc = "leaveRoomDesc";
  static const areYouSure = "areYouSure";
  static const leaveRoom = "leaveRoom";
  static const logoutDesc = "logoutDesc";
  static const deleteAccDesc = "deleteAccDesc";
  static const searchHere = "searchHere";
  static const remove = "remove";
  static const invite = "invite";
  static const invited = "invited";
  static const removeFromRoom = "removeFromRoom";
  static const makeAdmin = "makeAdmin";
  static const selectReason = "selectReason";
  static const tellUsMore = "tellUsMore";
  static const submitReport = "submitReport";
  static const deleteRoomDesc = "deleteRoomDesc";
  static const allMembers = "allMembers";
  static const admins = "admins";
  static const forYou = "forYou";
  static const platform = "platform";
  static const search = "search";
  static const update = "update";
  static const fullName = "fullName";
  static const profileVerificationDesc = "profileVerificationDesc";
  static const documentType = "documentType";
  static const selectDocument = "selectDocument";
  static const yourSelfie = "yourSelfie";
  static const capture = "capture";
  static const submit = "submit";
  static const pleaseSelectImage = "pleaseSelectImage";
  static const postAddedSuccessfully = 'postAddedSuccessfully';
  static const deletePostDesc = 'deletePostDesc';
  static const bio = 'bio';
  static const writeSomethingAboutYourSelf = 'writeSomethingAboutYourSelf';
  static const profileUpdatedSuccessfully = 'profileUpdatedSuccessfully';
  static const pleaseEnterRoomName = "pleaseEnterRoomName";
  static const pleaseEnterDescription = "pleaseEnterDescription";
  static const pleaseSelectAtLeast2Interests = "pleaseSelectAtLeast2Interests";
  static const reportPost = "reportPost";
  static const reportUser = "reportUser";
  static const likes = "likes";
  static const reportAddedSuccessfully = "reportAddedSuccessfully";
  static const pleaseEnterFullName = "pleaseEnterFullName";
  static const pleaseSelectDocument = "pleaseSelectDocument";
  static const pleaseEnterYourSelfie = "pleaseEnterYourSelfie";
  static const profileVerificationRequestSent = "profileVerificationRequestSent";
  static const verificationPending = "verificationPending";
  static const email = "email";
  static const password = "password";
  static const confirmPassword = "confirmPassword";
  static const register = "register";
  static const iHaveAnAccount = "iHaveAnAccount";
  static const signIn = "signIn";
  static const forgotPassword = "forgotPassword";
  static const forgotPasswordDisc = "forgotPasswordDisc";
  static const reset = "reset";
  static const continue_ = "continue_";
  static const doNtHaveAnAccount = "doNtHaveAnAccount";
  static const signUp = "signUp";
  static const passwordMismatched = "passwordMismatched";
  static const verificationLinkSent = "verificationLinkSent";
  static const pleaseVerifyToSignIn = "pleaseVerifyToSignIn";
  static const linkSendToReset = "linkSendToReset";
  static const noDataFound = "noDataFound";
  static const someThingWentWrong = 'someThingWentWrong';
  static const invitedSuccessfully = 'invitedSuccessfully';
  static const roomCreatedSuccessfully = 'roomCreatedSuccessfully';
  static const roomUpdatedSuccessfully = 'roomUpdatedSuccessfully';
  static const owner = 'owner';
  static const unBlock = 'unBlock';
  static const blockDesc = 'blockDesc';
  static const unblockDesc = 'unblockDesc';
  static const youAreBlocked = 'youAreBlocked';
  static const deleteChat = 'deleteChat';
  static const markAsRead = 'markAsRead';
  static const markAsUnread = 'markAsUnread';
  static const clearChatDesc = 'clearChatDesc';
  static const deleteChatDesc = 'deleteChatDesc';
  static const image = 'image';
  static const video = 'video';
  static const howDoYouWant = 'howDoYouWant';
  static const send = 'send';
  static const suggested = 'suggested';
  static const you = 'you';
  static const use = 'use';
  static const retake = 'retake';
  static const create = 'create';
  static const pleaseEnterUsername = 'pleaseEnterUsername';
  static const noPosts = 'noPosts';
  static const createPost = 'createPost';
  static const createStory = 'createStory';
  static const youCanNotSelectMoreThan = 'youCanNotSelectMoreThan';
  static const deleteCommentDisc = 'deleteCommentDisc';
  static const rejectInvitationDisc = 'invitationDisc';
  static const removeFromAdmin = 'removeFromAdmin';
  static const removeUserFromRoom = 'removeUserFromRoom';
  static const hasAcceptedYourJoinRequestOfRoom = 'hasAcceptedYourJoinRequestOfRoom';
  static const hasJoinedYourRoom = 'hasJoinedYourRoom';
  static const hasRequestedToJoinYourRoom = 'hasRequestedToJoinYourRoom';
  static const hasAcceptedYourInvitationOfRoom = 'hasAcceptedYourInvitationOfRoom';
  static const hasInvitedToRoom = 'hasInvitedToRoom';
  static const hasLikedYourPost = 'hasLikedYourPost';
  static const hasCommentedToYourPost = 'hasCommentedToYourPost';
  static const hasStartedFollowingYou = 'hasStartedFollowingYou';
  static const faqS = 'faqS';
  static const storyDeleteDisc = 'storyDeleteDisc';
  static const blockList = 'blockList';
  static const yourAccountBlocked = 'youAccountBlocked';
  static const yourAccountBlockedDisc = 'youAccountBlockedDisc';
  static const yesterday = "yesterday";
  static const anHourAgo = "anHourAgo";
  static const aMinuteAgo = "aMinuteAgo";
  static const justNow = "justNow";
  static const languages = "languages";
  static const showMore = "showMore";
  static const showLess = "showLess";
  static const rejectChatRequest = "rejectChatRequest";
  static const verificationDocumentTitle = "verificationDocumentTitle";
  static const verificationDocumentDesc = "verificationDocumentDesc";
  static const verificationSubscriptionTitle = "verificationSubscriptionTitle";
  static const verificationSubscriptionDesc = "verificationSubscriptionDesc";
  static const weekly = "weekly";
  static const monthly = "monthly";
  static const annual = "annual";
  static const lifetime = "lifetime";
  static const sixMonth = "sixMonth";
  static const threeMonth = "threeMonth";
  static const twoMonth = "twoMonth";
  static const subscriptionDesc = "subscriptionDesc";
  static const weAreOnlyAllow = "weAreOnlyAllow";
  static const minute = "minute";
  static const unMuteNotification = "unMuteNotification";
  static const method1 = "method1";
  static const method2 = "method2";
  static const pleaseConfigureSubscription = "pleaseConfigureSubscription";
  static const audio = "audio";
  static const spaces = "spaces";
  static const room = "room";
  static const messages = "messages";
  static const otherListeners = "otherListeners";
  static const endRoom = "endRoom";
  static const raiseHand = "raiseHand";
  static const micOn = "micOn";
  static const micOff = "micOff";
  static const hosts = "hosts";
  static const listeners = "listeners";
  static const startRoom = "startRoom";
  static const startNewRoom = "startNewRoom";
  static const visibility = "visibility";
  static const public = "public";
  static const publicAudioDesc = "publicAudioDesc";
  static const private = "private";
  static const privateAudioDesc = "privateAudioDesc";
  static const followersAudioDesc = "followersAudioDesc";
  static const selectHosts = "selectHosts";
  static const youCanAddHosts = "youCanAddHosts";
  static const startNow = "startNow";
  static const admin = "admin";
  static const noRequests = "noRequests";
  static const handRaised = "handRaised";
  static const requestHasBeenSetForHost = "requestHasBeenSetForHost";
  static const wantToMakeHostListener = "wantToMakeHostListener";
  static const adminHasMadeYouListener = "adminHasMadeYouListener";
  static const nowYouAreHost = "nowYouAreHost";
  static const wantToKickOutUser = "wantToKickOutUser";
  static const wantToRemoveUser = "wantToRemoveUser";
  static const adminHasKickedYouOut = "adminHasKickedYouOut";
  static const yes = "yes";
  static const wantToRejectRequest = "wantToRejectRequest";
  static const wantToEndTheRoom = "wantToEndTheRoom";
  static const noMessages = "noMessages";
  static const roomTiming = "roomTiming";
  static const roomEnded = "roomEnded";
  static const totalHosts = "totalHosts";
  static const totalListener = "totalListener";
  static const totalMembers = "totalMembers";
  static const close = "close";
  static const space = "space";
  static const ended = "ended";
  static const pleaseSelectAtLeastOneInterest = "pleaseSelectAtLeastOneInterest";
  static const addUsers = "addUsers";
  static const add = "add";
  static const added = "added";
  static const alreadyJoined = "alreadyJoined";
  static const done = "done";
  static const addedUsers = "addedUsers";
  static const hostLimitReached = "hostLimitReached";
  static const listenerLimitReached = "listenerLimitReached";
  static const spaceDurationReached = "spaceDurationReached";
  static const subscribe = "subscribe";
  static const youCanSelectHostFromSelectedUsers = "youCanSelectHostFromSelectedUsers";
  static const audioSpace = "audioSpace";
  static const audioSpaceDesc = "audioSpaceDesc";
  static const hasAddedYouTo = "hasAddedYouTo";
  static const asHost = "asHost";
  static const makeHost = "makeHost";
  static const rejectRequest = "rejectRequest";
  static const acceptRequest = "acceptRequest";
  static const mute = "mute";
  static const unmute = "unmute";
  static const removeFromHost = "removeFromHost";
  static const removeFromSpace = "removeFromSpace";
  static const removeTheUser = "removeTheUser";
  static const user = "user";
  static const host = "host";
  static const listener = "listener";
  static const choose = "choose";
  static const sendMessage = "sendMessage";
  static const storyHasBeenDeleted = "storyHasBeenDeleted";
  static const users = "users";
  static const posts = "posts";
  static const hashtags = "hashtags";
  static const mediaRejectedAndContainsSuchThings = "mediaRejectedAndContainsSuchThings";
  static const textRejectedAndContainsSuchThings = "textRejectedAndContainsSuchThings";
  static const doYouWantToRemoveThisRecording = "doYouWantToRemoveThisRecording";
  static const deletePostByModeratorDesc = "deletePostByModeratorDesc";
  static const deleteCommentByModeratorDesc = "deleteCommentByModeratorDesc";
  static const deleteRoomByModeratorDesc = "deleteRoomByModeratorDesc";
  static const deleteStoryByModeratorDesc = "deleteStoryByModeratorDesc";
  static const blockUserGloballyByModeratorDesc = "blockUserGloballyByModeratorDesc";
  static const blockGlobally = "blockGlobally";
  static const seeWhoLikedPost = "seeWhoLikedPost";
  static const removeThisAudio = "removeThisAudio";
  static const messageSent = "messageSent";
  static const skip = "skip";
  static const upload = "upload";
  static const story = "story";
  static const reels = "reels";
  static const explore = "explore";
  static const categories = "categories";
  static const saved = "saved";
  static const selectMusic = "selectMusic";
  static const musics = "musics";
  static const removeSelectedMusicDesc = "removeSelectedMusicDesc";
  static const addNewReel = "addNewReel";
  static const preview = "preview";
  static const changeCover = "changeCover";
  static const selectInterestToContinue = "selectInterestToContinue";
  static const views = "views";
  static const reportReel = "reportReel";
  static const useMusic = "useMusic";
  static const savedReels = "savedReels";
  static const deleteReelDesc = "deleteReelDesc";
  static const noReels = "noReels";
  static const noReelsFromFollowings = "noReelsFromFollowings";
  static const seeMoreReels = "seeMoreReels";
  static const hasLikedYourReel = 'hasLikedYourReel';
  static const hasCommentedToYourReel = 'hasCommentedToYourReel';
  static const restorePurchase = 'Restore Purchase';
  static const seconds = 'seconds';
  static const underMaintenance = 'Under Maintenance';
  static const updateTheApp = 'Update the App';
  static const UpdateTheAppDesc = 'This update is required to continue using the app. Please update now for security, stability, and performance improvements.';
}

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        Language.Arabic.languageCode: arabicStrings,
        Language.Chinese.languageCode: chineseStrings,
        Language.English.languageCode: englishStrings,
        Language.Danish.languageCode: danishStrings,
        Language.Dutch.languageCode: dutchStrings,
        Language.French.languageCode: frenchStrings,
        Language.German.languageCode: germanStrings,
        Language.Greek.languageCode: greekStrings,
        Language.Hindi.languageCode: hindiStrings,
        Language.Indonesian.languageCode: indonesianStrings,
        Language.Italian.languageCode: italianStrings,
        Language.Japanese.languageCode: japaneseStrings,
        Language.Korean.languageCode: koreanStrings,
        Language.Norwegian.languageCode: norwegianStrings,
        Language.Polish.languageCode: polishStrings,
        Language.Portuguese.languageCode: portugueseStrings,
        Language.Russian.languageCode: russianStrings,
        Language.Spanish.languageCode: spanishStrings,
        Language.Swedish.languageCode: swedishStrings,
        Language.Thai.languageCode: thaiStrings,
        Language.Turkish.languageCode: turkishStrings,
        Language.Vietnamese.languageCode: vietnameseStrings,
      };
}
